spring:
  application:
    name: ibdb
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <clientId>
            client-secret: <clientSecret>
  data:
    cassandra:
      keyspace-name: main
      username: <username>
      password: <password>
      schema-action: create_if_not_exists
      request:
        timeout: 15s
      connection:
        connect-timeout: 15s
        init-query-timeout: 15s

server:
  port: 8081

datastax.astra:
  secure-connect-bundle: secure-connect-ibdb.zip

astra.db:
  id: <id>
  region: europe-west1
  keyspace: main
  application.token: <token>


